import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NoahDioramaModel(props: any) {
  const { nodes, materials } = useGLTF('/dae_diorama_-_forest_loner.glb') as any
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[86.169, 41.928, 630.203]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_grass_3_0.geometry}
            material={materials.M_grass_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_grass_2_0.geometry}
            material={materials.M_grass_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_soil_dirt_0.geometry}
            material={materials.M_soil_dirt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_transiotions_0.geometry}
            material={materials.M_transiotions}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_rand_schwarz_0.geometry}
            material={materials.M_rand_schwarz}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_grass_1_0.geometry}
            material={materials.M_grass_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_wood1_0.geometry}
            material={materials.M_S_wood1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_dirt_0.geometry}
            material={materials.M_S_dirt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_t_general1_0.geometry}
            material={materials.M_t_general1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_assets_unique_0.geometry}
            material={materials.M_assets_unique}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_t_unique1_0.geometry}
            material={materials.M_t_unique1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_wood_2_0.geometry}
            material={materials.M_S_wood_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_wood3_0.geometry}
            material={materials.M_S_wood3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_s_wood4_0.geometry}
            material={materials.M_s_wood4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_bark1_0.geometry}
            material={materials.M_S_bark1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_decalls1_0.geometry}
            material={materials.M_decalls1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_Lada_0.geometry}
            material={materials.M_Lada}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_nature_atlas_0.geometry}
            material={materials.M_nature_atlas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_nature_atlas_0_1.geometry}
            material={materials.M_nature_atlas}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_nature_atlas_2_0.geometry}
            material={materials.M_nature_atlas_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_nature_atlas_2_0_1.geometry}
            material={materials.M_nature_atlas_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_additional_trims_0.geometry}
            material={materials.M_additional_trims}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_additional_trims_0_1.geometry}
            material={materials.M_additional_trims}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_additional_trims_0_2.geometry}
            material={materials.M_additional_trims}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_rock_0.geometry}
            material={materials.M_rock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_bricks_0.geometry}
            material={materials.M_bricks}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_metal_plate_2_0.geometry}
            material={materials.M_S_metal_plate_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_metal_plate_0.geometry}
            material={materials.M_S_metal_plate}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_fox_and_decal_0.geometry}
            material={materials.M_fox_and_decal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_oakbirch_tree_0.geometry}
            material={materials.M_oakbirch_tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_Oakleaves_0.geometry}
            material={materials.M_Oakleaves}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_birch_0.geometry}
            material={materials.M_birch}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_background_trees_0.geometry}
            material={materials.M_background_trees}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_Chainsaw_0.geometry}
            material={materials.M_Chainsaw}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Diorama_M_S_bark2_0.geometry}
            material={materials.M_S_bark2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dae_diorama_-_forest_loner.glb')
